Version 1
htmlacademy-yii/561851-task-force-1 pull request #10
Opened 2019-12-15 06:43 UTC by ArtemAnoshin

2019-12-25 07:51 UTC, nkolosov requested changes

2019-12-25 07:51 UTC, nkolosov commented on data/categories.sql
> +INSERT INTO categories (name,icon) VALUES ('Курьерские услуги','translation')
Сами получившиеся SQL не надо добавлять в репозиторий, лучше код из `index.php` перенести в отдельный файл типа `generate-sql.php`, всегда будет просто возможность его сгенерировать и всё

2019-12-25 07:51 UTC, nkolosov commented on index.php
> +    'data/categories.csv',
Всегда стоит указыввать путь с указанием текущей директории (`__DIR__` . '/data/categories.csv') и так далее

2019-12-25 07:51 UTC, nkolosov commented on data/tasks.sql
> +INSERT INTO tasks (dt_add,category_id,description,expire,name,address,budget,lat,long) VALUES ('2019-03-09','2','Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.','2019
SQL код в этой (и еще в нескольких других таблицах) не запустится на твоей БД.

2019-12-27 04:06 UTC, nkolosov requested changes

2019-12-27 04:06 UTC, nkolosov commented on index.php
> +    '0' => [
Зачем указывать ключи числовые? Если их не будет, они просто создадутся автоматически (тем более, что они нигде не используются)

2019-12-27 04:06 UTC, nkolosov commented on index.php
> +        'handler' => 'TaskForce\Helpers\Handlers\OpinionImport',
Лучше передавать сразу экземпляр нужного класса, что-то типа `'handler' => new TaskForce\Helpers\Handlers\OpinionImport()`

2019-12-27 04:06 UTC, nkolosov commented on src/Helpers/Handlers/CategoryImport.php
> +    public function correctedResults($row): array
Нужно указывать тип параметра,
`public function correctedResults(array $row): array`

2019-12-27 04:06 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +                if ($this->type === 'INSERT') {
Лучше эту обработку вынести в отдельные методы, чтобы получилось что-то в духе
`$query = $this->type === 'INSERT' ? $this->getInsertString($row) : $this->getUpdateString($row);`

2019-12-28 18:58 UTC, nkolosov requested changes

2019-12-28 18:58 UTC, nkolosov commented on generate-sql.php
> +<?php
При запуске скрипта локально обнаружил вот такие ошибки
```
nkolosov@cahill:~/Projects/task-force-aanoshin$ php generate-sql.php 
PHP Notice:  Undefined offset: 4 in /home/nkolosov/Projects/task-force-aanoshin/src/Helpers/Handlers/ProfileImport.php on line 22
PHP Notice:  Undefined offset: 2 in /home/nkolosov/Projects/task-force-aanoshin/src/Helpers/Handlers/ProfileImport.php on line 20
PHP Notice:  Undefined offset: 3 in /home/nkolosov/Projects/task-force-aanoshin/src/Helpers/Handlers/ProfileImport.php on line 21
PHP Notice:  Undefined offset: 4 in /home/nkolosov/Projects/task-force-aanoshin/src/Helpers/Handlers/ProfileImport.php on line 22
```

А во-вторых, после попытки применить изменения в БД на основе сгенерированных SQL получил вот такое
```
yii> INSERT INTO user (`email`,`name`,`pass`,`created_at`,`city_id`) VALUES ('kbuttress0@1und1.de','Karrie Buttress','JcfoKBYAB4k','2019-08-10',257)
[2019-12-29 01:45:58] [HY000][1364] Field 'birthday' doesn't have a default value
[2019-12-29 01:45:58] [HY000][1364] Field 'birthday' doesn't have a default value
```

Так что это пока что не работает

2019-12-28 18:58 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +        if (!$this->columns) {
Вообще, это не очень хорошо, полагаться на реализацию метода, в надежде, что она запишет данные в поле объекта, почему бы просто не сделать что-то в духе `$columns = $this->getColums()`, раз это больше нигде не используется?

2019-12-28 18:58 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +        $result = null;
В этой перемнной нет смысла, можно просто в конце написать `return null`

2019-12-28 18:58 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +        foreach ($this->result as $row) {
Получается следующий алгоритм, сначала целиком читаем файл, затем проходимся по этому массиву и создаем SQL, это можно делать сразу, прочитали строку - получили SQL

2019-12-28 18:58 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +    private $filename;
Нужен typehint для всех полей и для всех параметров и возвращаемых значений

2019-12-28 18:58 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +        $filename = $row['filename'] ?? $row['tablename'];
Когда читаешь этот код возникает вопрос: "Почему переменная называется "файл", а записываем мы в неё название таблицы?"

2019-12-28 18:58 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +        if (!file_exists($this->filename)) {
В принципе, filename` и прочее доступны ещё в конструкторе, можно открыть файл сразу при создании объекта и в случае проблемы мы до вызова `transform` не дойдем просто

2019-12-28 18:58 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +        $f = null;
Зачем? Переменная и так уничтожится в конце работы метода

2019-12-28 18:58 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +        $data = substr($data,0,-1);
Не, надо сделать так, чтобы лишних символов в конце просто не появлялось, это костыль :)

2020-01-07 07:08 UTC, nkolosov requested changes

2020-01-07 07:08 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +    public function __construct(string $filename, object $handler, string $sqlAction = 'INSERT')
Не надо указывать `object`, ты же можешь конкретизировать, что передается объект вполне конкретного класса

2020-01-07 07:08 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +        $filename = $row['filename'] ?? $row['tablename'];
Этот вопрос никуда не исчез :)

2020-01-07 07:08 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +                    $this->queries[] = $query;
С точки зрения ООП непонятно зачем записывать что-то в поле объекта, а затем это передавать параметром в другой метод этого же класса, ведь изнутри этого метода итак есть доступ к полям объекта

2020-01-07 07:08 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +    private function createSqlFile ($queries, $filename):void {
Не хватает type hint

2020-01-07 07:08 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +        $sqlFileName = $dir . $filename . ".sql";
"Куда записывать результат" тоже должно приходить параметром "снаружи", как и "откуда читать данные"

2020-01-07 07:08 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +    private function getInsertString ($row, $tablename):string {
type hint

2020-01-07 07:08 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +        $data = array();
Используй короткий синтаксис `[]`

2020-01-07 07:08 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +        $data = implode(',', $data);
До этой строчки методы `getInsertString` и `getUpdateString` не отличаются, получается дублирование кода

2020-01-07 07:08 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +        $query = "UPDATE " . $tablename . " SET " . $data . " WHERE `id`=" . rand(1,20) . ";";
А почему от 1 до 20? А если значений меньше?

2020-01-07 07:08 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +        $query = "UPDATE " . $tablename . " SET " . $data . " WHERE `id`=" . rand(1,20) . ";";
Или больше?

2020-01-07 07:08 UTC, nkolosov commented on generate-sql.php
> +$filesForTransform = [
Если затем пытать выполнить эти SQL в том порядке, что они перечислены тут - получается ошибка

2020-01-08 08:00 UTC, nkolosov requested changes

2020-01-08 08:00 UTC, nkolosov commented on generate-sql.php
> +        'sqlFileName' => 'category'
Надо также, указывать полный путь, как и для входного файла

2020-01-08 08:00 UTC, nkolosov commented on php.ini
> +error_reporting = 'E_ALL & ~E_DEPRECATED & ~E_STRICT';
Этот файл не должен быть в репозитории

2020-01-08 08:00 UTC, nkolosov commented on src/Helpers/Handlers/ProfileImport.php
> +                'birthday' => $row[1] ?? '0000-00-00',
Ну нет, `0000-00-00` - это плохо, дефолтное значение в таком случае тоже должно быть `null`

2020-01-08 08:00 UTC, nkolosov commented on src/Helpers/Handlers/UserImport.php
> +                'pass' => $row[2],
В базе пароль будет в открытом виде, так нельзя, надо использовать какое-нибудь хеширование

2020-01-08 08:00 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +     * @param $queries
phpdoc некорректный

2020-01-08 08:00 UTC, nkolosov commented on src/Helpers/Handlers/UserImport.php
> +                'created_at' => $row[3],
Может там, всё таки, `birthdate` ?

2020-01-08 08:00 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +        $this->filename = $filename;
Это поле, фактически, бесполезно, так как кроме конструктора нигде не используется

2020-01-08 08:00 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +        $this->columns = $this->fp->fgetcsv();
Это тоже не используется нигде кроме конструктора

2020-01-08 08:00 UTC, nkolosov commented on src/Helpers/TransformCsvToSql.php
> +    public function transform($sqlFileName):void
type hint

2020-01-08 08:37 UTC, ArtemAnoshin commented on src/Helpers/Handlers/UserImport.php
> +                'created_at' => $row[3],
dt_add - все таки это дата регистрации

2020-01-08 09:14 UTC, merged