Task ver.1 quets 2
htmlacademy-yii/561851-task-force-1 pull request #4
Opened 2019-11-02 02:10 UTC by ArtemAnoshin

2019-11-04 17:20 UTC, nkolosov requested changes

2019-11-04 17:20 UTC, nkolosov commented on Task.php
> +    const PLAYER = 'player';
`player` - странное наименование. Скорее уж `worker` или`employee`

2019-11-04 17:20 UTC, nkolosov commented on Task.php
> +    const CUSTOMER = 'customer';
Надо добавить префикс `const ROLE_CUSTOMER`

2019-11-04 17:20 UTC, nkolosov commented on Task.php
> +    private static $avaibleStatuses = [
Я совсем забыл, что в современном PHP можно не использовать статические переменные для массивов, а делать также, обычню константу, то есть `const ALL_STATUSES = [...]`, так будет правильнее

2019-11-04 17:20 UTC, nkolosov commented on Task.php
> +        assert($this->status == self::STATUS_NEW && $this->userRole == self::CUSTOMER);
Лучше не использовать `&&`, а сделать 2 assert подряд, тогда будет понятно какое именно условие не сработало

2019-11-04 17:20 UTC, nkolosov commented on Task.php
> +        return $this->status = self::STATUS_CANCELLED;
Не надо так делать, это стоит сделать отдельными строками в коде, то есть 
```
$this->status = self::STATUS_CANCELED;
return $this->status;
```

2019-11-04 17:20 UTC, nkolosov commented on Task.php
> +    public function cancel ()
Не хватает типа возвращаемого значения

2019-11-04 17:20 UTC, nkolosov commented on Task.php
> +    private $userRole = self::CUSTOMER;
`userRole` - это не свойство самого Task, он должен передаваться как параметр конкретного действия (типа $task->cancel($currentUserRole)`

2019-11-04 17:20 UTC, nkolosov commented on Task.php
> +        assert($this->status == self::STATUS_NEW && $this->userRole == self::CUSTOMER);
Кроме того, стоит использовать строгое сравнение `===`

2019-11-04 17:20 UTC, nkolosov commented on Task.php
> +    public function setStatus(string $status): void
Можно избавиться от всех set и задавать все эти параметры в конструкторе

2019-11-06 04:13 UTC, ArtemAnoshin commented on Task.php
> +    const PLAYER = 'player';
+

2019-11-06 04:15 UTC, ArtemAnoshin commented on Task.php
> +    const CUSTOMER = 'customer';
ready

2019-11-06 04:16 UTC, ArtemAnoshin commented on Task.php
> +    private static $avaibleStatuses = [
ready

2019-11-06 04:22 UTC, ArtemAnoshin commented on Task.php
> +        assert($this->status == self::STATUS_NEW && $this->userRole == self::CUSTOMER);
готово

2019-11-06 04:24 UTC, ArtemAnoshin commented on Task.php
> +        return $this->status = self::STATUS_CANCELLED;
готово

2019-11-06 04:26 UTC, ArtemAnoshin commented on Task.php
> +    public function cancel ()
готово

2019-11-06 05:53 UTC, nkolosov requested changes

2019-11-06 05:53 UTC, nkolosov commented on Task.php
> +    public function __construct($status = STATUS_NEW, $userRole = ROLE_CUSTOMER, $employeeId, $customerId, $completionDate)
1. Всё так же не хватает type hint, он должен быть всегда и везде.
2. Если у какого-то параметра есть дефолтное значение, то он должен быть в конце списка
3. Поле `userRole` удалено, а в конструктор всё еще передается и присваивается

2019-11-06 05:53 UTC, nkolosov commented on Task.php
> +    public function cancel ($currentUserRole): string
type hint `string $currentUserRole`

2019-11-06 05:53 UTC, nkolosov commented on Task.php
> +    public function getUserRole(): string
Надо удалить

2019-11-06 05:53 UTC, nkolosov commented on Task.php
> +     * @return mixed
Аналогично, должен быть не `mixed`, а `int`

2019-11-06 11:55 UTC, nkolosov requested changes

2019-11-06 11:55 UTC, nkolosov commented on Task.php
> +    public function __construct(int $employeeId, int $customerId, string $completionDate, string $status = STATUS_NEW)
Этот код просто не заработает, так как в этой строке присутствует ошибка `undefined constant`

И еще, в качестве типа для `$completionDate` лучше использовать `\DateTime`, а не `string`

2019-11-06 12:26 UTC, merged